### PR TITLE
fix definition of site.posts_by_language, site.pages_by_language;

### PR DESCRIPTION
**Pull request by kuka**

### CODE REVIEW

**Comment by NoahDragon** [comment]
Thanks, I'll try it on my site. :+1:

**Comment by liaohuqiu** [comment]
It's in `1.0.11`

**Comment by NoahDragon** [comment]
@kuka I have a problem while show the recent posts. I have used the site.posts_by_language, but the recent post still showing all language posts. The code snippet is showing below.

```html
<section>
  <h1>Recent Posts</h1>
  <ul id="recent_posts">
    {% for post in site.posts_by_language limit: site.recent_posts %}
      <li class="post">
        <a href="{{ root_url }}{{ post.url }}">{% if site.titlecase %}{{ post.title | titlecase }}{% else %}{{ post.title }}{% endif %}</a>
      </li>
    {% endfor %}
  </ul>
</section>
```

Any advise are appreciated.

**Comment by NoahDragon** [comment]
This fix does work for a while, but one day I checked my webpage, the block of recent posts shows nothing. The problem code is showing below:

``` html
<section>
  <h1>Recent Posts</h1>
  <ul id="recent_posts">
    {% for post in site.posts_by_language limit: site.recent_posts %}
      <li class="post">
        <a href="{{ root_url }}{{ post.url }}">{% if site.titlecase %}{{ post.title | titlecase }}{% else %}{{ post.title }}{% endif %}</a>
      </li>
    {% endfor %}
  </ul>
</section>
```

So I have to modified the code in my asides/Recent_Posts.html like following to kind of solved the issue.

``` html
<section>
  <h1>Recent Posts</h1>
  <ul id="recent_posts">
    {% assign count = 0 %}
    {% for post in site.posts %}
	{% if post.language == page.language %}
		{% if count == site.recent_posts %}
			{% break %}
		{% endif %}
		{% assign count = count | plus:1 %} 
      <li class="post">
        <a href="{{ root_url }}{{ post.url }}">{% if site.titlecase %}{{ post.title | titlecase }}{% else %}{{ post.title }}{% endif %}</a>
      </li>
	{% endif %}
    {% endfor %}
  </ul>
</section>
```

I don't know if the issue is really caused by the `site.posts_by_language`, but just paste my solution here to give others a hint if they have the similar issues.

**Pull request merged**
