### PR TITLE
add t tag for translated strings in templates

### PR DESCRIPTION
**Pull request by cbergmann**
I needed the t function for my templates.
This code is highly inspired (partwise direct copy) by https://github.com/screeninteraction/jekyll-multiple-languages-plugin They use the Mozilla public license.
As I understand it at least the newly intruduced file must be under MPL.
If you don't agree with this I can rewrite the code from scratch.

### CODE REVIEW

**Comment by liaohuqiu** [comment]
It's a great feature, but could you please rewrite it?  I would like to keep using MIT license, it's less constraint for the developer. Thank you in advance.

**Comment by cbergmann** [comment]
If you'r OK with it I would first try to contact the other developing Team and ask for a license exception.

**Comment by liaohuqiu** [comment]
@cbergmann . It's great :+1: . Thank you in advance.

**Comment by cbergmann** [comment]
The developer answered as follows:

> Hi Clemens
> 
> First, I’d like to thank you for you mail. However I don’t see the issue 
> since MPL as far as I know is fully GPL compatible:
> 
>     The MPL allows covered source code to be mixed with other files
>     under a different, even proprietary license. However, code files
>     licensed under the MPL must remain under the MPL and freely
>     available in source form. This makes the MPL a compromise between
>     the MIT or BSD licenses, which permit all derived works to be
>     relicensed as proprietary, and the GPL, which requires the whole of
>     a derived work, even new components, to remain under the GPL.
> 
> But it doesn’t much since I gladly give you a license exception for the 
> plugin. The reason for MPL and not MIT is just that it was part of a 
> bigger project which was MPL licensed.
> 
> I can probably change license as well if it would make your life easier :)
> 
> Regards
> 
> 
> 
> Martin Kurtsson

**Comment by liaohuqiu** [comment]
That's awesome!!! You are all great. So I can merge this pull request  and make a new release right now?

**Comment by cbergmann** [comment]
I would think so 


-------- Ursprüngliche Nachricht --------
Von: Huqiu Liao <notifications@github.com>
Gesendet: 10. März 2015 07:20:39 MEZ
An: liaohuqiu/jekyll-multiple-languages <jekyll-multiple-languages@noreply.github.com>
CC: Clemens Bergmann <cbergmann@schuhklassert.de>
Betreff: Re: [jekyll-multiple-languages] add t tag for translated strings in templates (#7)

That's awesome!!! You are all great. So I can merge this pull request  and make a new release right now?

---
Reply to this email directly or view it on GitHub:
https://github.com/liaohuqiu/jekyll-multiple-languages/pull/7#issuecomment-78001817
-- 
Diese Nachricht wurde von meinem Mobiltelefon gesendet.

**Comment by liaohuqiu** [comment]
`1.0.8` has been released: https://rubygems.org/gems/jekyll-multiple-languages. Thank you for your excellent work.

**Pull request merged**
